title: DMHub Official Documentation
description: The official documentation for DMHub, a free virtual tabletop solution. 
theme: just-the-docs
color_scheme: "goblin"
favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/logo.png"

plugins: 
    - jekyll_video_tag
    - api-leaf

markdown: kramdown

callouts:
  warning:
    title: Warning
    color: red
    callouts_level: loud
    opacity: 0.1

  important:
    title: Important
    color: yellow
    callouts_level: loud
    opacity: 0.1

  note:
    title: Note
    color: purple
    callouts_level: loud
    opacity: 0.1

  tip:
    title: Tip!
    color: green
    callouts_level: loud
    opacity: 0.1

url: https://just-the-docs.github.io

aux_links:
  Get DMHub: https://dmhubapp.com

# External navigation links
nav_external_links:
  - title: Github
    url: https://github.com/Phanterm/dmhub-docs
    hide_icon: false
    nav_external_links:
  - title: Discord
    url: https://discord.com/invite/DP8EQ4vUhd
    hide_icon: false

#Footer
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Phanterm/dmhub-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately